# Railway Deployment Configuration for Frontend
# https://docs.railway.app/deploy/config-as-code

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run preview -- --port $PORT --host 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
