[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'alembic upgrade head && uvicorn src.api.main:app --host 0.0.0.0 --port $PORT'
