# Railway Deployment Configuration for Backend
# https://docs.railway.app/deploy/config-as-code

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "alembic upgrade head && uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
